### ISSUE TITLE
Nice demo app

### ISSUE THREAD

**Issue by anton-pytel** [marekmichalik/quatro#1]
Hi Marek,

I'd like to reach out and say hello! We are Slovakia based small company specializing in IoT projects for international customers, looking for a new team member in Edge & Platform development team. Based on repo I'd like to get to know you better for possible cooperation. Let's have a talk?

[Anton Pytel](https://www.linkedin.com/in/anton-pytel-77547233/)
[MAKERS s. r. o.](https://www.linkedin.com/company/makers-sk/mycompany)

**Comment by marekmichalik** [comment]
Hi Anton!
Thank You, nice to hear about you and your company near me. Demo is modernised version of app written and lost 20 years ago in pascal/asm. Now I am pretty busy, especially as we are returning to office, but certainly it will be nice to stay in touch. Now I am covering a bit large test automation framework, using python 3 and selenium.

Best regards,
Marek

https://www.linkedin.com/in/marek-michal%C3%ADk-653b9011/

**Comment by anton-pytel** [comment]
Sure, thank you, I have connected you in linkedin. If you had some time for discussion feel free to reach us out. All the best.
